version: '3.8'

services:
  master:
    image: locustio/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089
    ports:
      - "8089:8089"
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  worker:
    image: locustio/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    extra_hosts:
      - "host.docker.internal:host-gateway"
