apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  labels:
    app: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: locust-master
        image: locustio/locust:latest
        command: ["locust", "-f", "/mnt/locust/locustfile.py", "--master", "-H", "http://master:8089"]
        ports:
        - name: loc-master-web
          containerPort: 8089
        - name: loc-master-p1
          containerPort: 5557
        - name: loc-master-p2
          containerPort: 5558
        volumeMounts:
        - name: locustfile
          mountPath: "/mnt/locust/"
          readOnly: true
      volumes:
      - name: locustfile
        configMap:
          name: locustfile
