apiVersion: v1
kind: Service
metadata:
  name: locust-master
spec:
  type: ClusterIP
  selector:
    app: locust-master
  ports:
  - name: loc-master-web
    port: 8089
    targetPort: loc-master-web
  - name: loc-master-p1
    port: 5557
    targetPort: loc-master-p1
  - name: loc-master-p2
    port: 5558
    targetPort: loc-master-p2
